name: Full Continuous Integration
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          cd frontend/
          npm install
      - name: Run Tests
        run: |
          cd frontend/
          npm run test_cloud
      - name: Run Linter
        run: |
          cd frontend/
          npm run lint

  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          cd backend/
          npm install
      - name: Run Tests
        run: |
          cd backend/
          npm run test
      - name: Run Linter
        run: |
          cd backend/
          npm run lint